workflows:
  flutter-workflow:
    name: Flutter Workflow
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: flutter pub get

      - name: Run tests
        script: flutter test
        args:
          - --no-pub
        test_report: build/junit.xml

      - name: Build Flutter app
        script: flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
